apiVersion: apps/v1
kind: Deployment
metadata:
  name: surveyformapi
  namespace: default
  labels:
    app: surveyformapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: surveyformapi
  template:
    metadata:
      name: surveyformapi
      labels:
        app: surveyformapi
    spec:
      containers:
        - name: surveyformrestapi
          image: uddeepyalamanchili/spring_crud_app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DB_PASSWORD
              value: Uddip_swe645!
      restartPolicy: Always
